config/routes.rb
AccPro::Application.routes.draw do
  devise_for :users

  resources :transactions

  resources :accounts

  root :to => redirect('/accounts')

end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_transaction, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @transactions = Transaction.all
    respond_with(@transactions)
  end

  def show
    respond_with(@transaction)
  end

  def new
    @transaction = Transaction.new
    @accounts = Account.all
    @direction_menu = [["From", "From"], ["To", "To"]]
    @account_menu = []
    @accounts.each do |account|
      @account_menu << [account.name, account.id]
    end
    respond_with(@transaction)
  end

  def edit
    @transaction = Transaction.find_by_id(params[:id])
    @accounts = Account.all
    @direction_menu = [["From", "From"], ["To", "To"]]
    @account_menu = []
    @accounts.each do |account|
      @account_menu << [account.name, account.id]
    end
    respond_with(@transaction)
  end

  def create
    @valid = false

    if ( ( (params[:transaction][:first_direction] == "From") and 
        (Account.find_by_id(params[:transaction][:first_account_id]).amount.to_i < params[:transaction][:amount].to_i) ) or
        ((params[:transaction][:second_direction] == "From") and 
        (Account.find_by_id(params[:transaction][:second_account_id]).amount.to_i < params[:transaction][:amount].to_i)) )
      flash[:notice] = "No enough money in your account."
      redirect_to :back
    else
      @valid = Account.validate_transaction(params[:transaction][:first_account_id], 
                                          params[:transaction][:first_direction], 
                                          params[:transaction][:second_account_id], 
                                          params[:transaction][:second_direction], 
                                          params[:transaction][:amount])
    if (@valid == true)
      @transaction = Transaction.new(params[:transaction])
      @transaction.save
      redirect_to transactions_path
    else
      flash[:notice] = "Transaction is invalid, please use proper accounts."
      redirect_to :back
    end

    end
    
  end

  def update
    @transaction.update_attributes(params[:transaction])
    respond_with(@transaction)
  end

  def destroy
    @transaction.destroy
    respond_with(@transaction)
  end

  private
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<%= form_for(@transaction) do |f| %>
  <% if @transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>

      <ul>
      <% @transaction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :first_direction, options_for_select(@direction_menu) %><br />
    <%= f.select :first_account_id, options_for_select(@account_menu) %><br />
  </div>
  <div class="field">
    <%= f.select :second_direction, options_for_select(@direction_menu) %><br />
    <%= f.select :second_account_id, options_for_select(@account_menu) %><br />
  </div>
  <div class="field">
    <%= f.label :Amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<h1>Editing transaction</h1>

<%= render 'form' %>

<%= link_to 'Show', @transaction %> |
<%= link_to 'Back', transactions_path %>

app/views/transactions/index.html.erb
<div id="wrapper">
<h1>Transactions Log</h1>

<table id="keywords" cellspacing="0" cellpadding="0">
  <tr>
    <th><span>To/From</span></th>
    <th><span>First Account</span></th>
    <th><span>To/From</span></th>
    <th><span>Second Account</span></th>
    <th><span>Amount</span></th>
    <th><span>Date</span></th>
  </tr>

<% @transactions.each do |transaction| %>
  <tr>
    <td class="lalign"><%= transaction.first_direction %></td>
    <td class="lalign"><%= Account.find_by_id(transaction.first_account_id).name %></td>
    <td class="lalign"><%= transaction.second_direction %></td>
    <td class="lalign"><%= Account.find_by_id(transaction.second_account_id).name %></td>
    <td class="lalign"><%= transaction.amount %></td>
    <td class="lalign"><%= transaction.created_at %></td>
    <td class="lalign"><%= link_to 'Show', transaction %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Transaction', new_transaction_path %>
<%= link_to 'Balance Sheet', accounts_path %>

app/views/transactions/new.html.erb
<h1>New transaction</h1>

<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: "field_with_errors" %>
<% end -%>

<p>
</P>

<%= render 'form' %>

<%= link_to 'Back', transactions_path %>

app/views/transactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= @transaction.first_direction %>: <b><%= @transaction.first_account_id %>
</p>

<p>
  <b><%= @transaction.second_direction %>: <b><%= @transaction.second_account_id %>
</p>

<p>
  <b>Amount:</b>
  <%= @transaction.amount %>
</p>


<%= link_to 'Back', transactions_path %>