config/routes.rb
AccPro::Application.routes.draw do
  devise_for :users

  resources :transactions

  resources :accounts

  root :to => redirect('/accounts')

end

app/models/account.rb
class Account < ActiveRecord::Base
  attr_accessible :name, :accounttype, :amount
  validates :name, :presence => true, :uniqueness => true, format: { with: /\A[a-zA-Z ]+\z/, message: "only allows letters, spaces" }
  validates :amount, :presence => true, numericality: { only_integer: true }

  def self.validate_transaction(account_1, account_1_direc, account_2, account_2_direc, amount)
    @asset = 0
    @expense = 0
    @liability = 0
    @equity = 0
    @accounts = Account.all
    @first_account = self.find_by_id(account_1)
    @second_account = self.find_by_id(account_2)

    @accounts.each do |account|
      if (account.accounttype == "Asset")
        @asset += account.amount.to_i
      elsif (account.accounttype == "Expense")
        @expense += account.amount.to_i
      elsif (account.accounttype == "Liability")
        @liability += account.amount.to_i
      elsif (account.accounttype == "Equity")
        @equity += account.amount.to_i
      end
    end

    if (@first_account.accounttype == "Asset")
      if (account_1_direc == "To")
        @asset += amount.to_i
      elsif (account_1_direc == "From")
        @asset -= amount.to_i
      end
    elsif (@first_account.accounttype == "Expense")
      if (account_1_direc == "To")
        @expense += amount.to_i
      elsif (account_1_direc == "From")
        @expense -= amount.to_i
      end
    elsif (@first_account.accounttype == "Liability")
      if (account_1_direc == "To")
        @liability += amount.to_i
      elsif (account_1_direc == "From")
        @liability -= amount.to_i
      end
    elsif (@first_account.accounttype == "Equity")
      if (account_1_direc == "To")
        @equity += amount.to_i
      elsif (account_1_direc == "From")
        @equity -= amount.to_i
      end
    end

    if (@second_account.accounttype == "Asset")
      if (account_2_direc == "To")
        @asset += amount.to_i
      elsif (account_2_direc == "From")
        @asset -= amount.to_i
      end
    elsif (@second_account.accounttype == "Expense")
      if (account_2_direc == "To")
        @expense += amount.to_i
      elsif (account_2_direc == "From")
        @expense -= amount.to_i
      end
    elsif (@second_account.accounttype == "Liability")
      if (account_2_direc == "To")
        @liability += amount.to_i
      elsif (account_2_direc == "From")
        @liability -= amount.to_i
      end
    elsif (@second_account.accounttype == "Equity")
      if (account_2_direc == "To")
        @equity += amount.to_i
      elsif (account_2_direc == "From")
        @equity -= amount.to_i
      end
    end

    if ( (@asset + @expense - @liability - @equity) == 0)
      if (account_1_direc == "To")
        Account.find_by_id(account_1).update_attributes(:amount => (amount.to_i + @first_account.amount.to_i))
      elsif (account_1_direc == "From")
        Account.find_by_id(account_1).update_attributes(:amount => (@first_account.amount.to_i - amount.to_i))
      end

      if (account_2_direc == "To")
        Account.find_by_id(account_2).update_attributes(:amount => (amount.to_i + @second_account.amount.to_i))
      elsif (account_2_direc == "From")
        Account.find_by_id(account_2).update_attributes(:amount => (@second_account.amount.to_i - amount.to_i))
      end

      return true
    else
      return false
    end
  end

end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource
  before_filter :set_account, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @account_types = [["Asset", "Asset"], ["Liability", "Liability"], ["Expense", "Expense"], ["Equity", "Equity"]]
    
    if (params[:account_type] == nil or params[:account_type] == "")
      @accounts = Account.all
    elsif
      @accounts = Account.find_all_by_accounttype(params[:account_type])
      @selected = params[:account_type]
    end
    respond_with(@accounts)
  end

  def show
    respond_with(@account)
  end

  def new
    @account_types = [["Asset", "Asset"], ["Liability", "Liability"], ["Expense", "Expense"], ["Equity", "Equity"]]
    @account = Account.new
    respond_with(@account)
  end

  def edit
    @account_types = [["Asset", "Asset"], ["Liability", "Liability"], ["Expense", "Expense"], ["Equity", "Equity"]]
    @account = Account.find_by_id(params[:id])
  end

  def create
    @account = Account.new(params[:account])

    if @account.valid?
      @account.save
      flash[:notice] = "#{@account.name} was successfully created."
      redirect_to accounts_path and return
    else
      redirect_to :back
    end
  end

  def update
    @account.update_attributes(params[:account])
    respond_with(@account)
  end

  def destroy
    @account.destroy
    respond_with(@account)
  end

  private
    def set_account
      @account = Account.find(params[:id])
    end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/_form.html.erb
<%= form_for(@account) do |f| %>
  <% if @account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@account.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :type %><br />
    <%= f.select :accounttype, options_for_select(@account_types) %>
  </div>

  <div class="field">
    <%= f.label :amount %><br />
    <%= f.number_field :amount %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/accounts/edit.html.erb
<h1>Editing account</h1>

<%= render 'form' %>

<%= link_to 'Show', @account %> |
<%= link_to 'Back', accounts_path %>

app/views/accounts/index.html.erb
<div id="wrapper">
<h1><%= link_to 'Balance Sheet', accounts_path %></h1>

<table id="keywords" cellspacing="0" cellpadding="0">

  <tr>
    <%= form_tag accounts_path, :id => "types_form", :method => :get do %>
      <%= label_tag(:t, "Filter accounts by Type") %>
      <%= select_tag(:account_type, options_for_select(@account_types, @selected)) %>
      <%= submit_tag("Filter") %>
    <% end %>
  </tr>

  <tr>
    <th><span>Name</span></th>
    <th><span>Type</span></th>
    <th><span>Amount</span></th>
  </tr>

<% @accounts.each do |account| %>
  <tr>
    <td class="lalign"><%= account.name %></td>
    <td class="lalign"><%= account.accounttype %></td>
    <td class="lalign"><%= account.amount %></td>
    <td class="lalign"><%= link_to 'Show', account %></td>
    <td class="lalign"><%= link_to 'Edit', edit_account_path(account) %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Account', new_account_path %>
<%= link_to 'New Transaction', new_transaction_path %>
</div>

app/views/accounts/new.html.erb
<h1>New account</h1>

<%= render 'form' %>

<%= link_to 'Back', accounts_path %>

app/views/accounts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @account.name %>
</p>

<p>
  <b>Type:</b>
  <%= @account.accounttype %>
</p>

<p>
  <b>Amount:</b>
  <%= @account.amount %>
</p>

<%= link_to 'Edit', edit_account_path(@account) %> |
<%= link_to 'Back', accounts_path %>